[versions]
logging = "1.5.22"
p4j = "1.8.4"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logging" }
password4j = { module = "com.password4j:password4j", version.ref = "p4j" }
